name: Welcome New Contributors

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome first-timers
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Hi! Thanks for opening your first issue on the **Expense Tracker** project. We’re happy to have you here!
          pr-message: |
            🎉 Thanks for your first pull request! We appreciate your contribution. A maintainer will review it soon.
